export { StudentProfilePage } from './StudentProfilePage'
export { TutorProfilePage } from './TutorProfilePage'
//export { TutorProfileViewPage } from './TutorProfileViewPage'
export { ParentProfilePage } from './ParentProfilePage'
export { ProfileRedirect } from './ProfileRedirect'